# Copyright 2019 Iced Development, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3"
services:
  members_api:
    container_name: members_api
    build: ../members_api
    depends_on:
      - members_postgres
    ports:
      - "3004:3004"
      - "9229:9229"
    environment:
      NODE_PORT: 3004
      NODE_ENV: "development"
      SENDGRID_API_KEY: "some big ass sendgrid key"
      DATABASE_URL: "postgres://postgres:postgres@members_postgres:5432/hsl_dev"
      JWT_KEY: "some random key"
      NPMINSTALL: 0 # set to 1 to run npm install after mounting volume
    # volumes:
    #   - ../members_api:/home/app

  members_ui:
    container_name: members_ui
    build: ../members_ui
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
      NODE_ENV: "development"
      REACT_APP_MEMBERS_API_URL: "http://localhost:3004" # use what's visible from the host machine; NO TRAILING SLASH
    # volumes:
    #   - ../members_ui:/home/app

  members_postgres:
    container_name: members_postgres
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hsl_dev

